# Generated by Django 4.2.6 on 2024-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='face_image',
            field=models.ImageField(default=1, max_length=255, upload_to='images/'),
            preserve_default=False,
        ),
    ]
