# Generated by Django 4.2.6 on 2024-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountmodel_face_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='face_image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
