# Generated by Django 4.2.6 on 2024-10-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_rating_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmodel',
            name='mean_point',
            field=models.FloatField(null=True),
        ),
    ]
